[package]
name = "random-walks"
version = "0.4.1"
entrypoint = "lib.typ"
authors = ["abiswas3"]
license = "MIT"
description = "Personal Typst theme for math/CS papers and lecture notes. Forked from theorion."
repository = "https://github.com/abiswas3/typst-theorion"
keywords = ["theorem", "corollary", "lemma", "html", "environment", "math", "box", "multilingual", "boxes", "colorful"]
disciplines = ["computer-science", "engineering", "mathematics", "physics", "education"]
categories = ["components"]
compiler = "0.13.0"
exclude = ["examples"]